need pull request
platzi/escuelajs-reto-03 pull request #14
Opened 2019-09-14 17:02 UTC by deveeup

## DESCRIPTION

Nombre: David R
Usuario Platzi: @deveeup

## Ciudad
- [ ] Ciudad de México
- [*] Bogotá

# Retos:
  - [*] Primer problema
  - [*] Segundo problema
  - [] Tercer problema

2019-09-16 19:20 UTC, deveeup commented
3. Promises.

2019-09-20 20:07 UTC, gndx requested changes

2019-09-20 20:07 UTC, gndx commented on src/index.js
> +const BASE_API = "https://rickandmortyapi.com/api/character/",
¡Genial!

2019-09-20 20:07 UTC, gndx commented on src/index.js
> +    }catch(error) {
Hay que tener cuidado con el indentado, si bien no es un factor que afecte la lógica de tu problema, si es un factor importante para la lectura del código. 

```suggestion
    }
    catch(error) {
```

2019-09-20 20:07 UTC, gndx commented on src/index.js
> +
Tratemos de no dejar espacios en nuestro código, si bien nos ayudan a detectar bloques de código, lo ideal es no abusar de este tipo de espacios.

2019-09-20 20:07 UTC, gndx commented on src/index.js
> +          const response = JSON.parse(xhr.responseText)
!Genial! 👍

2019-09-20 20:07 UTC, gndx commented on src/index.js
> +  return new Promise((res, rej) => {
Sugiero 
```suggestion
  return new Promise((response, reject) => {
```

2019-09-20 20:12 UTC, deveeup commented
Gracias por tu feedback @gndx  :)

2023-01-10 16:36 UTC, closed without merging