Reto 01
platzi/escuelajs-reto-03 pull request #23
Opened 2019-09-14 18:02 UTC by ealexisaraujo

## DESCRIPTION

Nombre: Enrique Alexis Lopez Araujo
Usuario Platzi: @alexisaraujo

## Ciudad
- [X] Ciudad de México
- [ ] Bogotá

# Retos:
  - [X] Primer problema
  - [ ] Segundo problema
  - [ ] Tercer problema

2019-09-20 20:40 UTC, gndx requested changes

2019-09-20 20:40 UTC, gndx commented on .gitignore
> +.node-xmlhttprequest-sync-20484
¿Por que estamos ignorando esto?

2019-09-20 20:40 UTC, gndx commented on ejemplo.html
> +<!DOCTYPE html>
Esto no es parte del reto, las instrucciones se encuentran en el README.md del repositorio.

2019-09-20 20:40 UTC, gndx commented on reto.html
> +<!DOCTYPE html>
Esto no es parte del reto, las instrucciones se encuentran en el README.md del repositorio.

2019-09-20 20:40 UTC, gndx commented on src/index.js
> +// Reto 3 resolviendo reto con promesas
Cuando mandamos un Pull Request debemos de eliminar los comentarios, Si bien son ayudas para nosotros, hay maneras mas efectivas de documentar. 

Te recomiendo leer al respecto en: https://devdocs.io/jsdoc/

2019-09-20 20:40 UTC, gndx commented on src/index.js
> +        else return todoMal(url_api);
Te recomiendo ser mas claros en el reject, esto te permite identificar el error mas fácil.

2019-09-20 20:40 UTC, gndx commented on src/index.js
> +        else return todoMal(url_api);
Aunque nuestra aplicación este en español, por convención nuestro código debe de estar en Ingles, el nombre de esta función esta en español.

2019-09-20 22:22 UTC, ealexisaraujo commented on .gitignore
> +.node-xmlhttprequest-sync-20484
Hola @gndx lo que hice fue agregar un .gitignore generico de https://www.gitignore.io/ que a lo mejor no deberia ser asi y cuando ejecutaba con node el archivo .node-xmlhttprequest-sync-20484 se agrego a los archivos por lo que asumi que podia ignorarlo

2019-09-20 22:23 UTC, ealexisaraujo commented on ejemplo.html
> +<!DOCTYPE html>
Este archivo "html" lo agregue por que leonidas esteban nos estaba mostrando un ejemplo de como funcionaba la libreria, por eso es que se fue este archivo .html dentro de la carpeta del reto

2019-09-20 22:24 UTC, ealexisaraujo commented on reto.html
> +<!DOCTYPE html>
Este archivo "html" lo agregue por que leonidas esteban nos estaba mostrando un ejemplo de como funcionaba la libreria, por eso es que se fue este archivo .html dentro de la carpeta del reto

2019-09-21 01:59 UTC, ealexisaraujo commented on ejemplo.html
> +<!DOCTYPE html>
Se agrego en el gitignore usar los archivos html

2019-09-21 01:59 UTC, ealexisaraujo commented on src/index.js
> +// Reto 3 resolviendo reto con promesas
Se eliminaron los comentarios

2019-09-21 01:59 UTC, ealexisaraujo commented on src/index.js
> +        else return todoMal(url_api);
Se cambiaron las funciones a ingles para ser mas convencionales

2019-09-21 02:00 UTC, ealexisaraujo commented on src/index.js
> +        else return todoMal(url_api);
Se agrego en el reject que mostrara como error el status de la peticion

2019-09-21 02:00 UTC, ealexisaraujo commented on reto.html
> +<!DOCTYPE html>
Se pusieron en el gitignore los archivos html que use como ejemplo

2022-08-29 22:47 UTC, closed without merging